alias sudo="sudo "
alias ls="ls -ahFGT"

alias R="R --quiet --no-save --no-restore"
alias R-devel="/Users/mikael/Desktop/.R/R-devel-build/bin/R --quiet --no-save --no-restore"
alias R-4.2="/Users/mikael/Desktop/.R/R-4.2-build/bin/R --quiet --no-save --no-restore"
alias R-4.1="/Users/mikael/Desktop/.R/R-4.1-build/bin/R --quiet --no-save --no-restore"
alias R-4.0="/Users/mikael/Desktop/.R/R-4.0-build/bin/R --quiet --no-save --no-restore"
alias R-3.6="/Users/mikael/Desktop/.R/R-3.6-build/bin/R --quiet --no-save --no-restore"
alias R-3.5="/Users/mikael/Desktop/.R/R-3.5-build/bin/R --quiet --no-save --no-restore"

alias discord="/Applications/Discord.app/Contents/MacOS/Discord"
alias emacs="/Applications/Emacs.app/Contents/MacOS/Emacs"
alias firefox="/Applications/Firefox.app/Contents/MacOS/firefox"
alias safari="/Applications/Safari.app/Contents/MacOS/Safari"
alias skype="/Applications/Skype.app/Contents/MacOS/Skype"
alias slack="/Applications/Slack.app/Contents/MacOS/Slack"
alias spotify="/Applications/Spotify.app/Contents/MacOS/Spotify"
alias systempreferences="/System/Applications/System\ Preferences.app/Contents/MacOS/System\ Preferences"
alias teams="/Applications/Microsoft\ Teams.app/Contents/MacOS/Teams"
alias thunderbird="/Applications/Thunderbird.app/Contents/MacOS/thunderbird"
alias vlc="/Applications/VLC.app/Contents/MacOS/VLC"
alias zoom="/Applications/zoom.us.app/Contents/MacOS/zoom.us"
alias zulip="/Applications/Zulip.app/Contents/MacOS/Zulip"

